### ISSUE TITLE
Error: https://registry.yarnpkg.com/@react-three%2fscissor: Not found

### ISSUE THREAD

**Issue by eriksachse** [pmndrs/react-three-scissor#2]
After trying to install this package, I get the following error-log by Yarn:

> Arguments: 
>   /usr/local/bin/node /opt/homebrew/Cellar/yarn/1.22.17_2/libexec/bin/yarn.js add @react-three/scissor
> 
> PATH: 
>   /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/sbin
> 
> Yarn version: 
>   1.22.17
> 
> Node version: 
>   16.14.0
> 
> Platform: 
>   darwin arm64
> 
> Trace: 
>   Error: https://registry.yarnpkg.com/@react-three%2fscissor: Not found
>       at Request.params.callback [as _callback] (/opt/homebrew/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:67029:18)
>       at Request.self.callback (/opt/homebrew/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:140883:22)
>       at Request.emit (node:events:520:28)
>       at Request.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:141855:10)
>       at Request.emit (node:events:520:28)
>       at IncomingMessage.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:141777:12)
>       at Object.onceWrapper (node:events:639:28)
>       at IncomingMessage.emit (node:events:532:35)
>       at endReadableNT (node:internal/streams/readable:1346:12)
>       at processTicksAndRejections (node:internal/process/task_queues:83:21)
> 
> npm manifest: 
>   {
>     "private": true,
>     "version": "0.0.0",
>     "scripts": {
>       "dev": "vite",
>       "build": "vite build",
>       "preview": "vite preview"
>     },
>     "dependencies": {
>       "@react-three/drei": "^8.10.7",
>       "@react-three/fiber": "^7.0.26",
>       "react": "^17.0.2",
>       "react-dom": "^17.0.2",
>       "three": "^0.138.0"
>     },
>     "devDependencies": {
>       "@vitejs/plugin-react": "^1.0.7",
>       "vite": "^2.8.0"
>     }
>   }
> 

How can I install this package? Is it any different?

**Comment by FarazzShaikh** [comment]
The package is unreleased and a work in progress as of yet. 

Take a look at https://github.com/FarazzShaikh/react-three-scissor for a different but released implementation
